name: CI

on:
  push:
    branches: [develop, main]
    paths:
      - "frontend/**"
  pull_request:
    branches: [develop]
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24.9.0"

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Run build
        run: npm run build
        working-directory: frontend

      - name: Run tests with coverage
        run: npm test -- --ci --bail --coverage
        working-directory: frontend
        continue-on-error: false

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: frontend/coverage
