name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24.9.0"

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Run build
        run: npm run build
        working-directory: frontend

      - name: Run tests
        run: npm test
        working-directory: frontend
